<script lang="ts">
	import { browser } from '$app/environment';
	import { page } from '$app/state';
	import { apiFetch, ApiError } from '$lib/api/client';
	import type { CatalogSetDetail, MatchDetail } from '$lib/api/types';
	import MatchMeter from '$lib/components/matches/MatchMeter.svelte';
	import SubstitutionStory from '$lib/components/matches/SubstitutionStory.svelte';
	import MissingPartsTable from '$lib/components/matches/MissingPartsTable.svelte';
	let setNum = $derived(page.params.set_num || (browser ? window.location.pathname.split('/').filter(Boolean).at(-1) : '') || '10497-1'); let data = $state<MatchDetail | null>(null); let error = $state(''); let tab = $state<'color' | 'equivalent' | 'missing'>('color'); let controller: AbortController | undefined; let requestId = 0; let catalogParts = $state<CatalogSetDetail['parts']>([]);
	const statusLabel = (status: MatchDetail['status']) => status === 'exact' ? 'Exact build' : status === 'substitution' ? 'Buildable with color swaps' : `Missing ${data?.counts.missing ?? 0}`;
	const colorSwaps = $derived((data?.substitutions ?? []).filter((item) => item.kind === 'color')); const equivalents = $derived((data?.substitutions ?? []).filter((item) => item.kind !== 'color'));
	const missingWithCatalog = $derived((data?.missing ?? []).map((item) => ({ ...item, ...catalogParts.find((part) => part.part_num === item.part_num && part.color_id === item.color_id) })));
	async function load() { controller?.abort(); const localController = new AbortController(); controller = localController; const localRequestId = ++requestId; data = null; catalogParts = []; error = ''; try { const match = await apiFetch<MatchDetail>(`/api/matches/${setNum}`, { signal: localController.signal }); if (localRequestId !== requestId) return; data = match; if (!colorSwaps.length && equivalents.length) tab = 'equivalent'; else if (!colorSwaps.length && !equivalents.length && match.missing.length) tab = 'missing'; if (match.missing.length) { const catalog = await apiFetch<CatalogSetDetail>(`/api/catalog/sets/${setNum}`, { signal: localController.signal }); if (localRequestId === requestId) catalogParts = catalog.parts; } } catch (cause) { if (localRequestId === requestId && (cause as DOMException).name !== 'AbortError') error = cause instanceof ApiError ? cause.message : 'Couldn’t load this match.'; } }
	$effect(() => { void load(); });
</script>
<svelte:head><title>{data ? `${data.name} · Buildable` : 'Set detail · Buildable'}</title></svelte:head>
{#if error}<p class="error" role="alert">{error} <button onclick={() => void load()}>Retry</button></p>{/if}
{#if data}<section class="bench"><div class="hero-image">{#if data.image_url}<img src={data.image_url} alt="" />{:else}▦{/if}</div><div class="intro"><p class="eyebrow">Builder’s Bench</p><h1>{data.name}</h1><p>{data.set_num} · {data.year ?? 'Year unknown'}{#if data.theme_name} · {data.theme_name}{/if} {#if data.has_local_overrides}<span class="correction">Local correction applied</span>{/if}</p><div class={`status ${data.status}`}>{statusLabel(data.status)}</div></div><MatchMeter counts={data.counts} percentExact={data.percent_exact} percentBuildable={data.percent_buildable}/><div class="counts"><span>Exact <strong>{data.counts.exact}</strong></span><span>Swaps <strong>{data.counts.color_substitution + data.counts.equivalence_substitution}</strong></span><span>Missing <strong>{data.counts.missing}</strong></span></div><div class="links"><a href={`/settings?set=${encodeURIComponent(data.set_num)}`}>Correct catalog data</a>{#if data.instructions_url}<a href={data.instructions_url} target="_blank" rel="noreferrer">Instructions</a>{/if}{#if data.external_url}<a href={data.external_url} target="_blank" rel="noreferrer">Set details</a>{/if}</div></section>
{#if data.warnings.length}<p class="warning">Inventory confidence is reduced by incomplete owned sets; match quantities use known inventory only.</p>{/if}
{#if data.status === 'exact'}<p class="complete">All required pieces match exactly. Viewing this result does not reserve inventory.</p>{:else}<section class="detail"><div role="tablist" aria-label="Match details">{#if colorSwaps.length}<button role="tab" aria-selected={tab === 'color'} onclick={() => tab = 'color'}>Color swaps ({colorSwaps.length})</button>{/if}{#if equivalents.length}<button role="tab" aria-selected={tab === 'equivalent'} onclick={() => tab = 'equivalent'}>Equivalent parts ({equivalents.length})</button>{/if}{#if data.missing.length}<button role="tab" aria-selected={tab === 'missing'} onclick={() => tab = 'missing'}>Missing pieces ({data.missing.length})</button>{/if}</div>{#if tab === 'color'}<SubstitutionStory entries={colorSwaps} kind="color"/>{:else if tab === 'equivalent'}<SubstitutionStory entries={equivalents} kind="equivalent"/>{:else}<MissingPartsTable items={missingWithCatalog}/>{/if}</section>{/if}{/if}
<style>
	.bench { display:grid; grid-template-columns:130px minmax(230px,1fr) minmax(150px,.5fr); gap:18px; align-items:center; padding:18px; border:1px solid var(--line); background:var(--surface); }.hero-image { display:grid; place-items:center; width:130px;height:130px;background:#ece6da;border-radius:6px;font-size:2rem; }.hero-image img { width:100%;height:100%;object-fit:contain; }.eyebrow{margin:0 0 5px;color:var(--red);font-size:.72rem;font-weight:800;letter-spacing:.11em;text-transform:uppercase}.intro h1{margin:0;letter-spacing:-.035em}.intro>p:not(.eyebrow){margin:.4rem 0 0;color:var(--ink-muted);font-size:.85rem}.correction{display:inline-block;margin-left:6px;color:var(--blue);font-weight:750}.status{margin-top:12px;font-size:.82rem;font-weight:800}.status.exact{color:var(--green)}.status.substitution{color:#765300}.status.missing{color:var(--red)}.counts{display:flex;gap:10px;grid-column:2}.counts span{font-size:.78rem;color:var(--ink-muted)}.counts strong{color:var(--ink);font-variant-numeric:tabular-nums}.links{display:flex;gap:12px;grid-column:3}.links a{color:var(--blue);font-size:.82rem;font-weight:700}.warning,.complete,.error{margin:14px 0;padding:10px 12px;border-left:3px solid var(--yellow);background:#fff8dd;font-size:.84rem}.complete{border-color:var(--green);background:#edf8ef}.error{border-color:var(--red);color:#8b1c28;background:#fff0ef}.error button{border:0;background:none;color:inherit;text-decoration:underline;cursor:pointer}.detail{margin-top:22px}.detail [role=tablist]{display:flex;gap:2px;margin-bottom:10px;border-bottom:1px solid var(--line)}.detail [role=tab]{padding:9px 12px;border:1px solid transparent;border-bottom:0;background:none;color:var(--ink-muted);font-weight:700;cursor:pointer}.detail [role=tab][aria-selected=true]{border-color:var(--line);background:var(--surface);color:var(--ink)}
	@media(max-width:719px){.bench{grid-template-columns:82px 1fr;gap:12px;padding:14px}.hero-image{width:82px;height:82px}.bench :global(.meter){grid-column:1/-1}.counts{grid-column:1/-1;flex-wrap:wrap}.links{grid-column:1/-1}.intro h1{font-size:1.45rem}}
</style>
