<script lang="ts">
	import { apiFetch, ApiError } from '$lib/api/client';
	import type { EquivalenceGroup, SettingsStatus } from '$lib/api/types';
	import CatalogImportPanel from '$lib/components/settings/CatalogImportPanel.svelte';
	import BackupPanel from '$lib/components/settings/BackupPanel.svelte';
	import EquivalenceEditor from '$lib/components/settings/EquivalenceEditor.svelte';
	import CorrectionEditor from '$lib/components/settings/CorrectionEditor.svelte';
	let status = $state<SettingsStatus | null>(null); let groups = $state<EquivalenceGroup[]>([]); let loadError = $state(''); let current = $state(''); let next = $state(''); let confirm = $state(''); let passwordMessage = $state(''); let passwordError = $state('');
	async function load() { loadError = ''; try { const [nextStatus, nextGroups] = await Promise.all([apiFetch<SettingsStatus>('/api/settings/status'), apiFetch<EquivalenceGroup[]>('/api/equivalence-groups')]); status = nextStatus; groups = nextGroups; } catch (cause) { loadError = cause instanceof ApiError ? cause.message : 'Couldn’t load settings.'; } }
	async function changePassword() { passwordError = ''; passwordMessage = ''; if (next !== confirm) { passwordError = 'New password and confirmation must match.'; return; } try { await apiFetch('/api/auth/password', { method: 'POST', body: { current_password: current, new_password: next } }); current = ''; next = ''; confirm = ''; passwordMessage = 'Password changed. All prior sessions have been logged out.'; } catch (cause) { passwordError = cause instanceof ApiError ? cause.message : 'Couldn’t change the password.'; } }
	$effect(() => { void load(); });
</script>
<svelte:head><title>Settings · What2Build</title></svelte:head>
<section class="page-head"><div><p class="eyebrow">Workshop administration</p><h1>Settings</h1><p>Keep the local catalog, matching rules, and recovery data in working order.</p></div></section>
{#if loadError}<p class="error" role="alert">{loadError} <button onclick={() => void load()}>Retry</button></p>{/if}
<div class="layout"><div class="stack"><div id="catalog-import"><CatalogImportPanel {status} onImported={load}/></div><CorrectionEditor/></div><div class="stack"><BackupPanel/><EquivalenceEditor {groups} onChanged={load}/><section class="panel password" aria-labelledby="password-title"><div><p class="eyebrow">Access</p><h2 id="password-title">Change shared password</h2></div><p class="muted">Changing the password ends all existing sessions except this one.</p><form onsubmit={(event) => { event.preventDefault(); void changePassword(); }}><label>Current password<input required type="password" autocomplete="current-password" bind:value={current}/></label><label>New password<input required type="password" autocomplete="new-password" bind:value={next}/></label><label>Confirm new password<input required type="password" autocomplete="new-password" bind:value={confirm}/></label><button class="primary">Change password</button></form>{#if passwordMessage}<p class="success" role="status">{passwordMessage}</p>{/if}{#if passwordError}<p class="error" role="alert">{passwordError}</p>{/if}</section></div></div>
<style>.page-head{margin-bottom:18px}.eyebrow{margin:0 0 5px;color:var(--red);font-size:.72rem;font-weight:800;letter-spacing:.11em;text-transform:uppercase}.page-head h1{margin:0;letter-spacing:-.035em}.page-head p:last-child{margin:.35rem 0 0;color:var(--ink-muted)}.layout{display:grid;grid-template-columns:1fr 1fr;gap:16px;align-items:start}.stack{display:grid;gap:16px}.panel{padding:18px;border:1px solid var(--line);background:var(--surface)}.panel h2{margin:0}.muted{color:var(--ink-muted);font-size:.84rem}.password form{display:grid;gap:9px}.password label{display:grid;gap:4px;font-size:.8rem;font-weight:750}.password input{padding:8px;border:1px solid var(--line);background:white}.primary{justify-self:start;padding:8px 10px;border:1px solid var(--ink);background:var(--red);color:white;font-weight:750;cursor:pointer}.success{color:var(--green);font-weight:700}.error{padding:10px 12px;border-left:3px solid var(--red);background:#fff0ef;color:#8b1c28}.error button{border:0;background:none;color:inherit;text-decoration:underline;cursor:pointer}@media(max-width:800px){.layout{grid-template-columns:1fr}}</style>
