<script lang="ts">
	import type { OwnedSet } from '$lib/api/types';
	let { owned, imageUrl, onEditMissing, onUpdate, onRemove }: { owned: OwnedSet; imageUrl?: string | null; onEditMissing: () => void; onUpdate: (changes: Partial<OwnedSet>) => void; onRemove: () => void } = $props();
	let previewOpen = $state(false);
	function setComplete(complete: boolean) { if (complete && (owned.unknown_missing_count || owned.unknown_missing_note) && confirm('Clear the unknown missing-piece warning? Known missing pieces will be kept.')) onUpdate({ completeness: 'complete', unknown_missing_count: 0, unknown_missing_note: null }); else onUpdate({ completeness: complete ? 'complete' : 'incomplete' }); }
</script>
<article class="owned-set">
	{#if imageUrl}<button class="set-preview" type="button" aria-label={`Preview ${owned.set_name} image`} aria-haspopup="dialog" onclick={() => previewOpen = true}><img class="set-thumb" src={imageUrl} alt={`${owned.set_name} set thumbnail`}/></button>{:else}<div class="set-mark" aria-hidden="true">{owned.set_num.split('-')[0]}</div>{/if}
	<div class="identity"><strong>{owned.set_name}</strong><span>{owned.set_num}</span>{#if owned.known_missing_total}<span class="missing">{owned.known_missing_total} known missing</span>{/if}</div>
	<div class="controls"><label>Quantity <input aria-label={`Quantity for ${owned.set_name}`} type="number" min="1" value={owned.quantity} oninput={(e) => onUpdate({ quantity: Number(e.currentTarget.value) })} /></label><label><input type="checkbox" checked={owned.completeness === 'complete'} onchange={(e) => setComplete(e.currentTarget.checked)} /> Complete</label><label>Notes <input aria-label={`Notes for ${owned.set_name}`} value={owned.notes ?? ''} onchange={(e)=>onUpdate({notes:e.currentTarget.value||null})}/></label><details><summary aria-label={`Set actions for ${owned.set_name}`}>•••</summary><button onclick={onEditMissing}>Edit missing pieces</button><button class="quiet" onclick={onRemove}>Remove</button></details></div>
	{#if owned.completeness === 'incomplete'}<div class="warning">⚠ Unknown missing pieces may affect confidence. <label>Unknown count <input type="number" min="0" value={owned.unknown_missing_count} oninput={(e)=>onUpdate({unknown_missing_count:Number(e.currentTarget.value)})}/></label><label>Note <input value={owned.unknown_missing_note ?? ''} oninput={(e)=>onUpdate({unknown_missing_note:e.currentTarget.value || null})}/></label></div>{/if}
</article>
{#if previewOpen && imageUrl}<div class="preview-backdrop" role="presentation" onclick={(event) => { if (event.target === event.currentTarget) previewOpen = false; }}><div class="preview-dialog" role="dialog" aria-modal="true" aria-labelledby={`preview-${owned.id}`}><header><h2 id={`preview-${owned.id}`}>{owned.set_name} image preview</h2><button type="button" aria-label="Close preview" onclick={() => previewOpen = false}>×</button></header><img src={imageUrl} alt={`${owned.set_name} set preview`} /></div></div>{/if}
<style>.owned-set{display:grid;grid-template-columns:86px 1fr auto;gap:14px;align-items:center;padding:16px 0;border-bottom:1px solid var(--line)}.set-preview{width:80px;height:80px;padding:0;border:1px solid var(--line);border-radius:6px;background:white;cursor:zoom-in;overflow:hidden}.set-mark,.set-thumb{width:80px;height:80px;max-width:100%;border-radius:6px}.set-mark{display:grid;place-items:center;background:var(--yellow);border:1px solid #cda81a;font-size:.82rem;font-weight:800}.set-thumb{display:block;object-fit:contain}.identity{display:grid;gap:2px}.identity span{font-size:.82rem;color:var(--ink-muted)}.identity .missing{color:var(--red);font-weight:700}.controls{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.controls label{font-size:.78rem;font-weight:650}.controls input[type=number]{width:52px;margin-left:4px;padding:4px;border:1px solid var(--line);background:var(--surface)}button{border:1px solid var(--ink);background:var(--surface);padding:6px 9px;border-radius:4px;font-size:.78rem;font-weight:700}.quiet{border-color:var(--line);color:var(--ink-muted)}.warning{grid-column:2/-1;color:#8a5911;font-size:.8rem}.preview-backdrop{position:fixed;inset:0;z-index:20;display:grid;place-items:center;padding:18px;background:#17171799}.preview-dialog{width:min(760px,100%);max-height:90vh;padding:16px;border:1px solid var(--ink);border-radius:8px;background:var(--surface);box-shadow:6px 6px #171717}.preview-dialog header{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:12px}.preview-dialog h2{margin:0;font-size:1rem}.preview-dialog header button{font-size:1.1rem;line-height:1}.preview-dialog>img{display:block;width:100%;max-height:70vh;object-fit:contain;background:white;border:1px solid var(--line);border-radius:6px}@media(max-width:719px){.owned-set{grid-template-columns:76px 1fr}.set-preview,.set-mark,.set-thumb{width:72px;height:72px}.controls,.warning{grid-column:1/-1}.preview-dialog{padding:12px}}</style>
