<script lang="ts">
	import { apiFetch } from '$lib/api/client'; import type { CatalogSetSummary } from '$lib/api/types';
	type Result = CatalogSetSummary & { remote?: boolean };
	let { onClose, onAdded }: { onClose: () => void; onAdded: () => void } = $props();
	let query=$state(''), results=$state<Result[]>([]), selected=$state<Result|null>(null), apiConfigured=$state(false), quantity=$state(1), completeness=$state<'complete'|'incomplete'>('complete'), notes=$state(''); let timer: ReturnType<typeof setTimeout>;
	$effect(()=>{ void apiFetch<{api_key_configured?:boolean}>('/api/settings/status').then((s)=>{apiConfigured=!!s.api_key_configured;if(apiConfigured&&query)void runSearch();}).catch(()=>{}); });
	async function runSearch(){if(!query.trim()){results=[];return;} const cached=await apiFetch<CatalogSetSummary[]>(`/api/catalog/sets?q=${encodeURIComponent(query)}&limit=10`); results=cached; if(!cached.length&&apiConfigured){ const remote=await apiFetch<Result[]>(`/api/catalog/remote-search?q=${encodeURIComponent(query)}&limit=10`); results=remote.map((item)=>({...item,theme_name:null,has_local_overrides:false,remote:true})); }} function search(){ clearTimeout(timer); timer=setTimeout(()=>void runSearch(),250); }
	async function add(){if(!selected)return; if(selected.remote)await apiFetch(`/api/catalog/lookup/${selected.set_num}`,{method:'POST'}); await apiFetch('/api/collection',{method:'POST',body:{set_num:selected.set_num,quantity,completeness,unknown_missing_count:0,notes:notes||null}});onAdded();onClose();}
</script>
<div class="backdrop" role="presentation"><div class="dialog" role="dialog" aria-modal="true" aria-labelledby="add-title"><header><h2 id="add-title">Add set</h2><button aria-label="Close" onclick={onClose}>×</button></header><label>Set number or name<input bind:value={query} oninput={search}/></label>{#if !selected}<div role="listbox">{#each results as item}<button role="option" aria-selected="false" onclick={()=>selected=item}>{item.set_num} {item.name}{#if item.remote} · Import from Rebrickable{/if}</button>{/each}</div>{:else}<p><strong>{selected.set_num} {selected.name}</strong></p><div class="details"><label>Quantity<input aria-label="Quantity" type="number" min="1" bind:value={quantity}/></label><label>Completeness<select bind:value={completeness}><option value="complete">Complete</option><option value="incomplete">Incomplete</option></select></label><label>Notes<input aria-label="Notes" bind:value={notes}/></label></div><button onclick={add}>Add to collection</button>{/if}{#if !results.length && query}<p class="help">Can’t find it? <a href="/settings">Import it manually or from a ZIP in Settings.</a></p>{/if}</div></div>
<style>.backdrop{position:fixed;inset:0;z-index:5;display:grid;place-items:center;padding:16px;background:#17171766}.dialog{width:min(480px,100%);padding:20px;background:var(--surface);border:1px solid var(--ink);box-shadow:6px 6px #171717}.dialog header{display:flex;justify-content:space-between}.dialog label,.details{display:grid;gap:6px;font-weight:700}.details{grid-template-columns:1fr 1fr;margin:12px 0}.details label:last-child{grid-column:1/-1}.dialog input,.dialog select{padding:8px;border:1px solid var(--ink);background:white}.dialog [role=listbox]{display:grid;margin:8px 0}.dialog [role=option]{text-align:left;padding:9px;border:1px solid var(--line);background:var(--surface)}button{font:inherit;border:1px solid var(--ink);padding:7px 10px;background:var(--yellow);font-weight:700}.help{color:var(--ink-muted);font-size:.82rem}</style>
