<script lang="ts">
	import type { OwnedSet } from '$lib/api/types';
	let { owned, onEditMissing, onUpdate, onRemove }: { owned: OwnedSet; onEditMissing: () => void; onUpdate: (changes: Partial<OwnedSet>) => void; onRemove: () => void } = $props();
	function setComplete(complete: boolean) { if (complete && (owned.unknown_missing_count || owned.unknown_missing_note) && confirm('Clear the unknown missing-piece warning? Known missing pieces will be kept.')) onUpdate({ completeness: 'complete', unknown_missing_count: 0, unknown_missing_note: null }); else onUpdate({ completeness: complete ? 'complete' : 'incomplete' }); }
</script>
<article class="owned-set">
	<div class="set-mark" aria-hidden="true">{owned.set_num.split('-')[0]}</div>
	<div class="identity"><strong>{owned.set_name}</strong><span>{owned.set_num}</span>{#if owned.known_missing_total}<span class="missing">{owned.known_missing_total} known missing</span>{/if}</div>
	<div class="controls"><label>Quantity <input aria-label={`Quantity for ${owned.set_name}`} type="number" min="1" value={owned.quantity} oninput={(e) => onUpdate({ quantity: Number(e.currentTarget.value) })} /></label><label><input type="checkbox" checked={owned.completeness === 'complete'} onchange={(e) => setComplete(e.currentTarget.checked)} /> Complete</label><button onclick={onEditMissing}>Edit missing pieces</button><button class="quiet" onclick={onRemove}>Remove</button></div>
	{#if owned.completeness === 'incomplete'}<div class="warning">⚠ Unknown missing pieces may affect confidence. <label>Unknown count <input type="number" min="0" value={owned.unknown_missing_count} oninput={(e)=>onUpdate({unknown_missing_count:Number(e.currentTarget.value)})}/></label><label>Note <input value={owned.unknown_missing_note ?? ''} oninput={(e)=>onUpdate({unknown_missing_note:e.currentTarget.value || null})}/></label></div>{/if}
</article>
<style>.owned-set{display:grid;grid-template-columns:42px 1fr auto;gap:12px;align-items:center;padding:14px 0;border-bottom:1px solid var(--line)}.set-mark{display:grid;place-items:center;width:40px;height:40px;background:var(--yellow);border:1px solid #cda81a;border-radius:4px;font-size:.7rem;font-weight:800}.identity{display:grid;gap:2px}.identity span{font-size:.82rem;color:var(--ink-muted)}.identity .missing{color:var(--red);font-weight:700}.controls{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.controls label{font-size:.78rem;font-weight:650}.controls input[type=number]{width:52px;margin-left:4px;padding:4px;border:1px solid var(--line);background:var(--surface)}button{border:1px solid var(--ink);background:var(--surface);padding:6px 9px;border-radius:4px;font-size:.78rem;font-weight:700}.quiet{border-color:var(--line);color:var(--ink-muted)}.warning{grid-column:2/-1;color:#8a5911;font-size:.8rem}@media(max-width:719px){.owned-set{grid-template-columns:40px 1fr}.controls,.warning{grid-column:1/-1}}</style>
