<script lang="ts">
	import { browser } from '$app/environment';
	import { goto } from '$app/navigation';
	import { apiFetch, ApiError } from '$lib/api/client';
	import type { CatalogSetSummary, MatchStatus, Recommendation, RecommendationsResponse } from '$lib/api/types';
	import RecommendationFilters from '$lib/components/matches/RecommendationFilters.svelte';
	import RecommendationRow from '$lib/components/matches/RecommendationRow.svelte';

	type SearchResult = CatalogSetSummary & { remote?: boolean };
	const params = browser ? new URLSearchParams(window.location.search) : new URLSearchParams();
	let statuses = $state<Record<MatchStatus, boolean>>({ exact: params.get('exact') !== '0', substitution: params.get('substitution') !== '0', missing: params.get('missing') === '1' });
	let maxPieces = $state(params.get('max_pieces') ?? ''); let theme = $state(params.get('theme') ?? ''); let yearFrom = $state(params.get('year_from') ?? ''); let yearTo = $state(params.get('year_to') ?? ''); let sort = $state(params.get('sort') ?? 'buildability');
	let data = $state<RecommendationsResponse | null>(null); let error = $state(''); let loading = $state(false); let controller: AbortController | undefined;
	let targetQuery = $state(''); let targetResults = $state<SearchResult[]>([]); let searchError = $state(''); let apiConfigured = $state(false); let searchTimer: ReturnType<typeof setTimeout>;
	const themes = $derived([...new Set((data?.items ?? []).map((item) => item.theme_name).filter((value): value is string => Boolean(value)))].sort());
	function query() { const value = new URLSearchParams(); const selected = (Object.entries(statuses).filter(([, active]) => active).map(([status]) => status)).join(','); if (selected) value.set('status', selected); if (maxPieces) value.set('max_pieces', maxPieces); if (theme) value.set('theme', theme); if (yearFrom) value.set('year_from', yearFrom); if (yearTo) value.set('year_to', yearTo); if (sort !== 'buildability') value.set('sort', sort); return value; }
	function syncUrl() { if (browser) window.history.replaceState({}, '', `${window.location.pathname}${query().size ? `?${query()}` : ''}`); }
	async function load() { controller?.abort(); controller = new AbortController(); loading = true; error = ''; syncUrl(); try { data = await apiFetch<RecommendationsResponse>(`/api/recommendations?${query()}`, { signal: controller.signal }); if (!maxPieces) maxPieces = String(data.max_pieces); } catch (cause) { if ((cause as DOMException).name !== 'AbortError') error = cause instanceof ApiError ? cause.message : 'Couldn’t load buildable sets.'; } finally { if (!controller.signal.aborted) loading = false; } }
	function refresh() { void load(); }
	function searchTargets() { clearTimeout(searchTimer); searchTimer = setTimeout(async () => { const value = targetQuery.trim(); if (!value) { targetResults = []; return; } searchError = ''; try { const cached = await apiFetch<CatalogSetSummary[]>(`/api/catalog/sets?q=${encodeURIComponent(value)}&limit=8`); targetResults = cached; if (!cached.length && apiConfigured) { const remote = await apiFetch<SearchResult[]>(`/api/catalog/remote-search?q=${encodeURIComponent(value)}&limit=8`); targetResults = remote.map((item) => ({ ...item, theme_name: null, has_local_overrides: false, remote: true })); } } catch { searchError = 'Couldn’t search the catalog. Try again.'; } }, 220); }
	async function chooseTarget(item: SearchResult) { if (item.remote) await apiFetch(`/api/catalog/lookup/${item.set_num}`, { method: 'POST' }); await goto(`/sets/${item.set_num}`); }
	$effect(() => { void load(); void apiFetch<{ api_key_configured: boolean }>('/api/settings/status').then((value) => apiConfigured = value.api_key_configured).catch(() => {}); });
</script>
<svelte:head><title>Buildable Sets · What2Build</title></svelte:head>
<section class="page-head"><div><p class="eyebrow">Buildable sets</p><h1>What can you build?</h1><p>Match cached official sets against your full available inventory.</p></div></section>
<section class="target-search" aria-label="Build target search"><label>Search a build target<input placeholder="Set number or name" bind:value={targetQuery} oninput={searchTargets}/></label>{#if targetResults.length}<div role="listbox">{#each targetResults as item}<button role="option" aria-selected="false" onclick={() => void chooseTarget(item)}>{item.set_num} · {item.name}{#if item.remote} <small>Import from Rebrickable</small>{/if}</button>{/each}</div>{/if}{#if searchError}<p class="inline-error">{searchError} <button onclick={searchTargets}>Retry</button></p>{/if}</section>
<RecommendationFilters bind:statuses bind:maxPieces bind:theme bind:yearFrom bind:yearTo bind:sort {themes} onChange={refresh}/>
{#if error}<p class="error" role="alert">{error} <button onclick={refresh}>Retry</button></p>{/if}
<section class="results" aria-busy={loading}><div class="results-head"><strong>{data?.total_candidates ?? 0} matches</strong>{#if loading}<span>Refreshing…</span>{/if}</div>{#each data?.items ?? [] as item}<RecommendationRow {item} onOpen={(setNum) => void goto(`/sets/${setNum}`)}/>{/each}{#if !loading && data && !data.items.length}<p class="empty">No cached sets match these filters.</p>{/if}</section>
<style>
	.page-head { display:flex; justify-content:space-between; gap:16px; margin-bottom:18px; }.eyebrow { margin:0 0 5px; color:var(--red); font-size:.72rem; font-weight:800; letter-spacing:.11em; text-transform:uppercase; }h1 { margin:0; letter-spacing:-.035em; } .page-head p:last-child { margin:.35rem 0 0;color:var(--ink-muted); }.target-search { position:relative; margin-bottom:10px; }.target-search label { display:grid; gap:5px; max-width:560px; color:var(--ink-muted); font-size:.75rem; font-weight:750; }.target-search input { min-height:40px; border:1px solid var(--line); border-radius:5px; padding:8px 10px; background:var(--surface); color:var(--ink); }.target-search [role=listbox] { position:absolute; z-index:2; width:min(560px,100%); border:1px solid var(--line); background:white; box-shadow:0 8px 20px #241c1020; }.target-search [role=option] { display:block; width:100%; padding:9px 10px; border:0; border-bottom:1px solid var(--line); background:white; text-align:left; cursor:pointer; }.target-search small { color:var(--blue); }.inline-error,.error { color:#8b1c28; font-size:.82rem; }.inline-error button,.error button { border:0;background:none;color:inherit;text-decoration:underline;cursor:pointer; }.results { margin-top:14px; border:1px solid var(--line); }.results-head { display:flex; justify-content:space-between; padding:9px 10px; color:var(--ink-muted); font-size:.78rem; background:#eee8dc; }.empty { padding:18px; color:var(--ink-muted); }
</style>
