<script lang="ts">
	import { browser } from '$app/environment';
	import { goto } from '$app/navigation';
	import { apiFetch, ApiError } from '$lib/api/client';
	import type { CatalogSetSummary, MatchStatus, Recommendation, RecommendationsResponse } from '$lib/api/types';
	import RecommendationFilters from '$lib/components/matches/RecommendationFilters.svelte';
	import RecommendationRow from '$lib/components/matches/RecommendationRow.svelte';

	type SearchResult = CatalogSetSummary & { remote?: boolean };
	const params = browser ? new URLSearchParams(window.location.search) : new URLSearchParams();
	const sharedStatuses = params.get('status');
	const restoredStatuses = new Set(sharedStatuses === 'none' ? [] : sharedStatuses?.split(',').filter((value): value is MatchStatus => value === 'exact' || value === 'substitution' || value === 'missing'));
	let statuses = $state<Record<MatchStatus, boolean>>({ exact: sharedStatuses ? restoredStatuses.has('exact') : true, substitution: sharedStatuses ? restoredStatuses.has('substitution') : true, missing: sharedStatuses ? restoredStatuses.has('missing') : false });
	let maxPieces = $state(params.get('max_pieces') ?? ''); let theme = $state(params.get('theme') ?? ''); let yearFrom = $state(params.get('year_from') ?? ''); let yearTo = $state(params.get('year_to') ?? ''); let sort = $state(params.get('sort') ?? 'buildability'); let includeOwned = $state(params.get('include_owned') !== '0');
	let data = $state<RecommendationsResponse | null>(null); let error = $state(''); let loading = $state(false); let controller: AbortController | undefined; let requestId = 0;
	let targetQuery = $state(''); let targetResults = $state<SearchResult[]>([]); let searchError = $state(''); let apiConfigured = $state(false); let searchTimer: ReturnType<typeof setTimeout>; let importError = $state(''); let selectedRemote = $state<SearchResult | null>(null);
	const themes = $derived([...new Set((data?.items ?? []).map((item) => item.theme_name).filter((value): value is string => Boolean(value)))].sort());
	function query() { const value = new URLSearchParams(); const selected = (Object.entries(statuses).filter(([, active]) => active).map(([status]) => status)).join(','); value.set('status', selected || 'none'); value.set('hide_owned', String(!includeOwned)); if (!includeOwned) value.set('include_owned', '0'); if (maxPieces) value.set('max_pieces', maxPieces); if (theme) value.set('theme', theme); if (yearFrom) value.set('year_from', yearFrom); if (yearTo) value.set('year_to', yearTo); if (sort !== 'buildability') value.set('sort', sort); return value; }
	function syncUrl() { if (browser) window.history.replaceState({}, '', `${window.location.pathname}${query().size ? `?${query()}` : ''}`); }
	async function load() { controller?.abort(); const localController = new AbortController(); controller = localController; const localRequestId = ++requestId; const selected = Object.values(statuses).some(Boolean); loading = true; error = ''; syncUrl(); if (!selected) { data = { items: [], total_candidates: 0, offset: 0, limit: 50, max_pieces: Number(maxPieces) || 0, theme: theme || null, year_from: yearFrom ? Number(yearFrom) : null, year_to: yearTo ? Number(yearTo) : null, hide_owned: !includeOwned, status: [], sort: 'buildability', direction: 'asc' }; loading = false; return; } try { const response = await apiFetch<RecommendationsResponse>(`/api/recommendations?${query()}`, { signal: localController.signal }); if (localRequestId !== requestId) return; data = response; if (!maxPieces) maxPieces = String(response.max_pieces); } catch (cause) { if (localRequestId === requestId && (cause as DOMException).name !== 'AbortError') error = cause instanceof ApiError ? cause.message : 'Couldn’t load buildable sets.'; } finally { if (localRequestId === requestId) loading = false; } }
	function refresh() { void load(); }
	function searchTargets() { clearTimeout(searchTimer); searchTimer = setTimeout(async () => { const value = targetQuery.trim(); if (!value) { targetResults = []; return; } searchError = ''; try { const cached = await apiFetch<CatalogSetSummary[]>(`/api/catalog/sets?q=${encodeURIComponent(value)}&limit=8`); targetResults = cached; if (!cached.length && apiConfigured) { const remote = await apiFetch<SearchResult[]>(`/api/catalog/remote-search?q=${encodeURIComponent(value)}&limit=8`); targetResults = remote.map((item) => ({ ...item, theme_name: null, has_local_overrides: false, remote: true })); } } catch { searchError = 'Couldn’t search the catalog. Try again.'; } }, 220); }
	async function chooseTarget(item: SearchResult) { importError = ''; if (!item.remote) { await goto(`/sets/${item.set_num}`); return; } selectedRemote = item; try { await apiFetch(`/api/catalog/lookup/${item.set_num}`, { method: 'POST' }); selectedRemote = null; await goto(`/sets/${item.set_num}`); } catch { importError = `Couldn’t import ${item.name}.`; } }
	$effect(() => { void load(); void apiFetch<{ api_key_configured: boolean }>('/api/settings/status').then((value) => apiConfigured = value.api_key_configured).catch(() => {}); });
</script>
<svelte:head><title>Buildable Sets · Buildable</title></svelte:head>
<section class="page-head"><div><p class="eyebrow">Buildable sets</p><h1>What can you build?</h1><p>Match cached official sets against your full available inventory.</p></div></section>
<section class="target-search" aria-label="Build target search"><label>Search a build target<input placeholder="Set number or name" bind:value={targetQuery} oninput={searchTargets}/></label>{#if targetResults.length}<div role="listbox">{#each targetResults as item}<button role="option" aria-selected="false" onclick={() => void chooseTarget(item)}>{item.set_num} · {item.name}{#if item.remote} <small>Import from Rebrickable</small>{/if}</button>{/each}</div>{:else if targetQuery && !apiConfigured}<p class="help">Not in the cached catalog. <a href="/settings">Import a ZIP or add a set manually in Settings.</a></p>{/if}{#if searchError}<p class="inline-error">{searchError} <button onclick={searchTargets}>Retry</button></p>{/if}{#if importError}<p class="inline-error" role="alert">{importError} <button onclick={() => selectedRemote && void chooseTarget(selectedRemote)}>Retry import</button></p>{/if}</section>
<div class="view-options"><label><input type="checkbox" bind:checked={includeOwned} onchange={refresh}/>Include owned sets</label></div>
<RecommendationFilters bind:statuses bind:maxPieces bind:theme bind:yearFrom bind:yearTo bind:sort {themes} onChange={refresh}/>
{#if error}<p class="error" role="alert">{error} <button onclick={refresh}>Retry</button></p>{/if}
<section class="results" aria-busy={loading}><div class="results-head"><strong>{data?.total_candidates ?? 0} matches</strong>{#if loading}<span>Refreshing…</span>{/if}</div>{#each data?.items ?? [] as item}<RecommendationRow {item} onOpen={(setNum) => void goto(`/sets/${setNum}`)}/>{/each}{#if !loading && !Object.values(statuses).some(Boolean)}<p class="empty">No match statuses are selected.</p>{:else if !loading && data && !data.items.length}<div class="empty guidance"><h2>No sets match this view yet.</h2><p>Catalog imports add set references and inventories for matching. They do not add owned sets to your collection.</p><div class="guidance-links"><a href="/settings#catalog-import">Import a Rebrickable catalog ZIP</a><a href="/collection">Add owned sets</a></div><p>Start with exact builds and color swaps, then turn on missing-piece matches to find close candidates. Near misses are useful when a tiny parts order would unlock a set.</p><p>To broaden this page, raise the maximum pieces value, search a specific target above, or add a catalog set manually in Settings.</p></div>{/if}</section>
<style>
	.page-head { display:flex; justify-content:space-between; gap:16px; margin-bottom:18px; }.eyebrow { margin:0 0 5px; color:var(--red); font-size:.72rem; font-weight:800; letter-spacing:.11em; text-transform:uppercase; }h1 { margin:0; letter-spacing:-.035em; } .page-head p:last-child { margin:.35rem 0 0;color:var(--ink-muted); }.target-search { position:relative; margin-bottom:10px; }.target-search label { display:grid; gap:5px; max-width:560px; color:var(--ink-muted); font-size:.75rem; font-weight:750; }.target-search input { min-height:40px; border:1px solid var(--line); border-radius:5px; padding:8px 10px; background:var(--surface); color:var(--ink); }.target-search [role=listbox] { position:absolute; z-index:2; width:min(560px,100%); border:1px solid var(--line); background:white; box-shadow:0 8px 20px #241c1020; }.target-search [role=option] { display:block; width:100%; padding:9px 10px; border:0; border-bottom:1px solid var(--line); background:white; text-align:left; cursor:pointer; }.target-search small { color:var(--blue); }.view-options { display:flex; gap:12px; align-items:center; margin-bottom:10px; padding:10px 12px; border:1px solid var(--line); background:var(--surface); }.view-options label { display:flex; gap:7px; align-items:center; color:var(--ink); font-size:.8rem; font-weight:760; }.inline-error,.error { color:#8b1c28; font-size:.82rem; }.inline-error button,.error button { border:0;background:none;color:inherit;text-decoration:underline;cursor:pointer; }.results { margin-top:14px; border:1px solid var(--line); }.results-head { display:flex; justify-content:space-between; padding:9px 10px; color:var(--ink-muted); font-size:.78rem; background:#eee8dc; }.empty { padding:18px; color:var(--ink-muted); }.guidance { display:grid; gap:8px; }.guidance h2 { margin:0; color:var(--ink); font-size:1rem; }.guidance p { margin:0; max-width:760px; }.guidance-links { display:flex; flex-wrap:wrap; gap:8px; }.guidance-links a { padding:7px 9px; border:1px solid var(--line); color:var(--ink); background:white; font-size:.8rem; font-weight:760; text-decoration:none; }.guidance-links a:hover { border-color:var(--ink-muted); background:var(--paper); }
</style>
