<script lang="ts">
	import { Download } from 'lucide-svelte';
	import { apiFetch, ApiError } from '$lib/api/client';
	import type { BackupValidation, RestoreSummary } from '$lib/api/types';
	let backup = $state<Record<string, unknown> | null>(null); let filename = $state(''); let validation = $state<BackupValidation | null>(null); let error = $state(''); let replaceText = $state(''); let mode = $state<'merge' | 'replace'>('merge'); let restoring = $state(false); let restored = $state<RestoreSummary | null>(null);
	const plural = (count: number, word: string) => `${count} ${word}${count === 1 ? '' : 's'}`;
	function exportFilename(header: string | null) { return header?.match(/filename="?([^";]+)"?/)?.[1] ?? null; }
	async function exportBackup() { error = ''; try { const response = await fetch('/api/backups/export', { credentials: 'include' }); if (!response.ok) throw new ApiError(response.status, undefined, response.statusText); const serverFilename = exportFilename(response.headers.get('Content-Disposition')); if (!serverFilename) throw new Error('Backup export did not provide a filename.'); const data = await response.json(); const objectUrl = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = objectUrl; link.download = serverFilename; link.click(); URL.revokeObjectURL(objectUrl); } catch (cause) { error = cause instanceof ApiError ? cause.message : cause instanceof Error ? cause.message : 'Couldn’t export the backup.'; } }
	async function chooseFile(event: Event) { const file = (event.currentTarget as HTMLInputElement).files?.[0]; if (!file) return; error = ''; validation = null; restored = null; backup = null; filename = file.name; let payload: Record<string, unknown> | null = null; try { payload = JSON.parse(await file.text()) as Record<string, unknown>; const response = await apiFetch<BackupValidation>('/api/backups/validate', { method: 'POST', body: payload }); backup = payload; validation = response; } catch (cause) { if (payload && cause instanceof ApiError && cause.problem.missing_dependencies) { backup = payload; validation = { valid: false, missing_dependencies: cause.problem.missing_dependencies }; error = cause.message; } else error = cause instanceof SyntaxError ? 'This backup is not valid JSON.' : cause instanceof ApiError ? cause.message : 'Couldn’t validate this backup.'; } }
	function count(field: string) { return Array.isArray(backup?.[field]) ? (backup?.[field] as unknown[]).length : 0; }
	function dependencyText() { return Object.entries(validation?.missing_dependencies ?? {}).flatMap(([kind, values]) => values.map((value) => `${kind}: ${value}`)); }
	async function restore() { if (!backup || !validation || (mode === 'replace' && replaceText !== 'REPLACE')) return; restoring = true; error = ''; restored = null; try { restored = await apiFetch<RestoreSummary>(`/api/backups/import?mode=${mode}&confirm=${mode === 'replace'}`, { method: 'POST', body: backup }); } catch (cause) { error = cause instanceof ApiError ? cause.message : 'Couldn’t restore this backup.'; } finally { restoring = false; } }
</script>
<section class="panel" aria-labelledby="backup-title"><div class="heading"><div><p class="eyebrow">Recovery</p><h2 id="backup-title">Backup and restore</h2></div><button class="icon" aria-label="Download backup" title="Download backup" onclick={() => void exportBackup()}><Download size={17}/></button></div><p class="muted">Export your collection and local catalog rules. Secrets and password data are never included.</p><label class="file">Backup file<input aria-label="Backup file" type="file" accept="application/json,.json" onchange={chooseFile}/></label>{#if filename}<p class="muted">Selected: {filename}</p>{/if}{#if validation && backup}<p class="success">{plural(count('owned_sets'), 'owned set')}, {plural(count('equivalence_groups'), 'equivalence group')}</p>{#if dependencyText().length}<p class="error" role="alert">Restore is disabled until catalog dependencies are available: {dependencyText().join(', ')}. <a href="#catalog-import">Import the catalog first.</a></p>{:else}<fieldset><legend>Restore mode</legend><label><input type="radio" bind:group={mode} value="merge"/> Merge into local data</label><label><input type="radio" bind:group={mode} value="replace"/> Replace local data</label></fieldset>{#if mode === 'replace'}<label class="confirm">Type REPLACE to confirm<input aria-label="Type REPLACE to confirm" bind:value={replaceText}/></label><p class="warning">A safety backup is created before local data is replaced.</p>{/if}<button class="primary" disabled={restoring || (mode === 'replace' && replaceText !== 'REPLACE')} onclick={() => void restore()}>{mode === 'replace' ? 'Replace local data' : 'Merge local data'}</button>{/if}{/if}{#if restored}<p class="success" role="status">Restored {restored.changed} records.{#if restored.safety_backup} Safety backup saved as <strong>{restored.safety_backup}</strong>.{/if}</p>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}</section>
<style>.panel{padding:18px;border:1px solid var(--line);background:var(--surface)}.heading{display:flex;justify-content:space-between;gap:12px}.heading h2{margin:0}.eyebrow{margin:0 0 4px;color:var(--red);font-size:.7rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.icon{display:grid;place-items:center;width:35px;height:35px;border:1px solid var(--ink);background:var(--surface);cursor:pointer}.muted{color:var(--ink-muted);font-size:.84rem}.file,.confirm{display:grid;gap:5px;max-width:420px;font-size:.8rem;font-weight:750}.file input,.confirm input{padding:7px;border:1px solid var(--line);background:white}.success{color:var(--green);font-weight:700}.error{color:#8b1c28;font-size:.84rem}.warning{color:#765300;font-size:.84rem}fieldset{display:grid;gap:8px;margin:14px 0;padding:10px;border:1px solid var(--line)}fieldset label{font-size:.86rem}.primary{margin-top:12px;padding:8px 10px;border:1px solid var(--ink);background:var(--red);color:white;font-weight:750;cursor:pointer}.primary:disabled{opacity:.45;cursor:not-allowed}</style>
