<script lang="ts">
	import { apiFetch, ApiError } from '$lib/api/client';
	import type { ImportSummary, SettingsStatus } from '$lib/api/types';
	let { status, onImported }: { status: SettingsStatus | null; onImported: () => void } = $props();
	let importing = $state(false); let error = $state(''); let summary = $state<ImportSummary | null>(null); let manual = $state(false);
	let setNum = $state(''); let name = $state(''); let year = $state(''); let theme = $state(''); let rows = $state([{ part_num: '', part_name: '', color_id: '', color_name: '', rgb_hex: '', quantity: '1', is_spare: false }]);
	async function upload(event: Event) { const file = (event.currentTarget as HTMLInputElement).files?.[0]; if (!file) return; importing = true; error = ''; summary = null; try { const body = new FormData(); body.set('file', file); summary = await apiFetch<ImportSummary>('/api/catalog/import', { method: 'POST', body }); onImported(); } catch (cause) { error = cause instanceof ApiError ? cause.message : 'Couldn’t import this ZIP.'; } finally { importing = false; } }
	function addRow() { rows = [...rows, { part_num: '', part_name: '', color_id: '', color_name: '', rgb_hex: '', quantity: '1', is_spare: false }]; }
	async function saveManual() { error = ''; try { await apiFetch('/api/catalog/manual-sets', { method: 'POST', body: { set_num: setNum, name, year: year ? Number(year) : null, theme_name: theme || null, parts: rows.map((row) => ({ ...row, color_id: Number(row.color_id), quantity: Number(row.quantity), rgb_hex: row.rgb_hex.replace('#', '') })) } }); manual = false; onImported(); } catch (cause) { error = cause instanceof ApiError ? cause.message : 'Couldn’t save the manual set.'; } }
</script>
<section class="panel" aria-labelledby="catalog-title"><div class="heading"><div><p class="eyebrow">Catalog candidates</p><h2 id="catalog-title">Buildable set data</h2></div><span class:ok={status?.api_key_configured}>{status?.api_key_configured ? 'API key configured' : 'No API key configured'}</span></div><p class="muted">Import set references and inventories so Buildable Sets has candidates to match against. This does not add sets to your collection.</p><p class="muted">API keys are configured on the server and are never displayed or entered here.</p><div class="actions"><label class="button secondary">Choose Rebrickable ZIP<input aria-label="Catalog ZIP" type="file" accept=".zip" onchange={upload}/></label><button class="secondary" onclick={() => manual = true}>Add set manually</button></div>{#if importing}<p aria-live="polite">Importing catalog ZIP…</p>{/if}{#if summary}<p class="success" role="status">Imported {summary.sets} sets, {summary.parts} parts, and {summary.colors} colors for matching.</p>{#if summary.warnings.length}<ul class="warning">{#each summary.warnings as warning}<li>{warning}</li>{/each}</ul>{/if}{/if}{#if status?.last_successful_import}<p class="muted">Last successful import: {new Date(status.last_successful_import).toLocaleString()}</p>{/if}{#if status?.latest_failed_import}<p class="error" role="alert">Latest import failed: {new Date(status.latest_failed_import).toLocaleString()}</p>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}</section>
{#if manual}<div class="backdrop"><form class="dialog" onsubmit={(event) => { event.preventDefault(); void saveManual(); }}><header><h2>Add catalog set manually</h2><button type="button" aria-label="Close" onclick={() => manual = false}>×</button></header><div class="grid"><label>Set number<input required pattern="[0-9]+-[1-9][0-9]*" bind:value={setNum}/></label><label>Set name<input required bind:value={name}/></label><label>Year<input type="number" bind:value={year}/></label><label>Theme<input bind:value={theme}/></label></div><h3>Inventory rows</h3>{#each rows as row, index}<div class="row"><input aria-label={`Part number ${index + 1}`} placeholder="Part #" required bind:value={row.part_num}/><input aria-label={`Part name ${index + 1}`} placeholder="Part name" required bind:value={row.part_name}/><input aria-label={`Color ID ${index + 1}`} placeholder="Color ID" required type="number" bind:value={row.color_id}/><input aria-label={`Color name ${index + 1}`} placeholder="Color" required bind:value={row.color_name}/><input aria-label={`RGB hex ${index + 1}`} placeholder="RGB hex" required bind:value={row.rgb_hex}/><input aria-label={`Quantity ${index + 1}`} required min="1" type="number" bind:value={row.quantity}/><label class="check"><input type="checkbox" bind:checked={row.is_spare}/>Spare</label></div>{/each}<button class="secondary" type="button" onclick={addRow}>Add inventory row</button><footer><button type="button" class="secondary" onclick={() => manual = false}>Cancel</button><button class="primary">Save catalog set</button></footer></form></div>{/if}
<style>.panel{padding:18px;border:1px solid var(--line);background:var(--surface)}.heading{display:flex;justify-content:space-between;gap:12px;align-items:start}.heading h2{margin:0}.eyebrow{margin:0 0 4px;color:var(--red);font-size:.7rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.heading span{padding:4px 7px;background:#eee8dc;color:var(--ink-muted);font-size:.72rem;font-weight:700}.heading span.ok{background:#e7f5eb;color:var(--green)}.muted{color:var(--ink-muted);font-size:.84rem}.actions,footer{display:flex;flex-wrap:wrap;gap:8px}.button,button{padding:8px 10px;border:1px solid var(--ink);font-weight:750;cursor:pointer}.primary{background:var(--red);color:white}.secondary{background:var(--surface);color:var(--ink)}.button input{position:absolute;width:1px;height:1px;opacity:0}.success{color:var(--green);font-weight:700}.warning,.error{color:#8b1c28;font-size:.84rem}.backdrop{position:fixed;inset:0;z-index:10;display:grid;place-items:center;padding:16px;background:#17171777}.dialog{width:min(920px,100%);max-height:90vh;overflow:auto;padding:20px;border:1px solid var(--ink);background:var(--surface);box-shadow:6px 6px #171717}.dialog header{display:flex;justify-content:space-between}.dialog h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.grid label{display:grid;gap:4px;font-weight:700}.row{display:grid;grid-template-columns:1fr 1.5fr .7fr 1fr .8fr .6fr auto;gap:5px;margin:6px 0}.dialog input{min-width:0;padding:7px;border:1px solid var(--line)}.check{font-size:.75rem;white-space:nowrap}@media(max-width:719px){.grid,.row{grid-template-columns:1fr 1fr}.row input:nth-child(2){grid-column:span 1}.dialog{padding:16px}}</style>
