<script lang="ts">
	import { browser } from '$app/environment';
	import { apiFetch, ApiError } from '$lib/api/client';
	import type { CatalogSetDetail, SetCorrection } from '$lib/api/types';
	let setNum = $state(''); let correction = $state<SetCorrection | null>(null); let error = $state(''); let saving = $state(false); let reason = $state(''); let name = $state(''); let year = $state(''); let theme = $state(''); let numParts = $state('');
	async function load() { if (!setNum.trim()) return; error = ''; correction = null; try { const set = await apiFetch<CatalogSetDetail>(`/api/catalog/sets/${encodeURIComponent(setNum.trim())}`); const found = await apiFetch<SetCorrection>(`/api/overrides/sets/${encodeURIComponent(setNum.trim())}`).catch(() => null); correction = found ?? { imported: { name: set.name, year: set.year, theme_name: set.theme_name, num_parts: set.num_parts, image_url: set.image_url, external_url: set.external_url, instructions_url: set.instructions_url }, override: null, effective: { name: set.name, year: set.year, theme_name: set.theme_name, num_parts: set.num_parts, image_url: set.image_url, external_url: set.external_url, instructions_url: set.instructions_url }, has_local_overrides: set.has_local_overrides }; name = String(correction.effective.name ?? ''); year = correction.effective.year == null ? '' : String(correction.effective.year); theme = String(correction.effective.theme_name ?? ''); numParts = String(correction.effective.num_parts ?? ''); } catch (cause) { error = cause instanceof ApiError ? cause.message : 'Couldn’t load that catalog set.'; } }
	async function save() { if (!correction || !reason.trim()) { error = 'A correction reason is required.'; return; } saving = true; error = ''; try { correction = await apiFetch<SetCorrection>(`/api/overrides/sets/${encodeURIComponent(setNum.trim())}`, { method: 'PUT', body: { name: name || null, year: year ? Number(year) : null, theme_name: theme || null, num_parts: numParts ? Number(numParts) : null, reason: reason.trim() } }); } catch (cause) { error = cause instanceof ApiError ? cause.message : 'Couldn’t save the correction.'; } finally { saving = false; } }
	$effect(() => { const requestedSet = browser ? new URLSearchParams(window.location.search).get('set') : null; if (requestedSet) { setNum = requestedSet; void load(); } });
</script>
<section class="panel" aria-labelledby="correction-title"><div><p class="eyebrow">Correction layer</p><h2 id="correction-title">Correct catalog data</h2></div><p class="muted">Imported records remain unchanged. Local corrections take effect in inventory and matching.</p><div class="search"><label>Set number<input placeholder="e.g. 10497-1" bind:value={setNum}/></label><button class="secondary" onclick={() => void load()}>Load set</button></div>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if correction}<div class="comparison"><div><h3>Imported</h3><dl><dt>Name</dt><dd>{String(correction.imported.name ?? '—')}</dd><dt>Year</dt><dd>{String(correction.imported.year ?? '—')}</dd><dt>Theme</dt><dd>{String(correction.imported.theme_name ?? '—')}</dd><dt>Parts</dt><dd>{String(correction.imported.num_parts ?? '—')}</dd></dl></div><form onsubmit={(event) => { event.preventDefault(); void save(); }}><h3>Local / effective</h3><label>Name<input bind:value={name}/></label><label>Year<input type="number" bind:value={year}/></label><label>Theme<input bind:value={theme}/></label><label>Parts<input type="number" min="0" bind:value={numParts}/></label><label>Correction reason<input required bind:value={reason}/></label><button class="primary" disabled={saving}>Save correction</button></form><div><h3>Effective</h3><dl><dt>Name</dt><dd>{name || '—'}</dd><dt>Year</dt><dd>{year || '—'}</dd><dt>Theme</dt><dd>{theme || '—'}</dd><dt>Parts</dt><dd>{numParts || '—'}</dd></dl></div></div>{/if}</section>
<style>.panel{padding:18px;border:1px solid var(--line);background:var(--surface)}h2{margin:0}.eyebrow{margin:0 0 4px;color:var(--red);font-size:.7rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.muted{color:var(--ink-muted);font-size:.84rem}.search{display:flex;gap:8px;align-items:end}.search label{display:grid;gap:4px;font-size:.8rem;font-weight:750}.search input,form input{padding:7px;border:1px solid var(--line);background:white}.secondary,.primary{padding:8px 10px;border:1px solid var(--ink);font-weight:750;cursor:pointer}.secondary{background:var(--surface)}.primary{background:var(--red);color:white}.comparison{display:grid;grid-template-columns:1fr 1.15fr 1fr;gap:14px;margin-top:16px;padding-top:12px;border-top:1px solid var(--line)}.comparison h3{margin:0 0 8px;font-size:.88rem}.comparison form{display:grid;gap:7px}.comparison form label{display:grid;gap:3px;font-size:.75rem;font-weight:750}.comparison dl{margin:0;font-size:.82rem}.comparison dt{margin-top:7px;color:var(--ink-muted)}.comparison dd{margin:1px 0}.error{color:#8b1c28;font-size:.84rem}@media(max-width:719px){.comparison{grid-template-columns:1fr}.search{align-items:stretch;flex-direction:column}}</style>
