<script lang="ts">
	import { apiFetch, ApiError } from '$lib/api/client';
	import type { EquivalenceGroup } from '$lib/api/types';
	let { groups = [], onChanged }: { groups?: EquivalenceGroup[]; onChanged: () => void } = $props();
	let editing = $state<EquivalenceGroup | null>(null); let creating = $state(false); let name = $state(''); let notes = $state(''); let query = $state(''); let members = $state<string[]>([]); let error = $state(''); let deleting = $state<EquivalenceGroup | null>(null);
	function start(group?: EquivalenceGroup) { creating = !group; editing = group ?? null; name = group?.name ?? ''; notes = group?.notes ?? ''; members = [...(group?.part_nums ?? [])]; query = ''; error = ''; }
	function addMember() { const value = query.trim(); if (!value) return; if (members.includes(value)) { error = 'That part is already in this group.'; return; } members = [...members, value]; query = ''; error = ''; }
	async function save() { if (members.length < 2) { error = 'Add at least two distinct catalog parts.'; return; } error = ''; try { await apiFetch(editing ? `/api/equivalence-groups/${editing.id}` : '/api/equivalence-groups', { method: editing ? 'PUT' : 'POST', body: { name, notes: notes || null, part_nums: members } }); creating = false; editing = null; onChanged(); } catch (cause) { error = cause instanceof ApiError ? cause.message : 'Couldn’t save this equivalence group.'; } }
	async function remove() { if (!deleting) return; try { await apiFetch(`/api/equivalence-groups/${deleting.id}`, { method: 'DELETE' }); deleting = null; onChanged(); } catch (cause) { error = cause instanceof ApiError ? cause.message : 'Couldn’t delete this group.'; } }
</script>
<section class="panel" aria-labelledby="equivalence-title"><div class="heading"><div><p class="eyebrow">Matching rules</p><h2 id="equivalence-title">Part equivalence groups</h2></div><button class="primary" onclick={() => start()}>New equivalence group</button></div><p class="muted">Use only for deliberate non-color substitutions. A part may belong to one group.</p>{#if error && !creating && !editing}<p class="error" role="alert">{error}</p>{/if}<div class="groups">{#each groups as group (group.id)}<article><div><strong>{group.name}</strong><p>{group.part_nums.join(' · ')}</p>{#if group.notes}<small>{group.notes}</small>{/if}</div><div><button class="secondary" onclick={() => start(group)}>Edit</button><button class="danger" onclick={() => deleting = group}>Delete</button></div></article>{/each}{#if !groups.length}<p class="muted">No equivalence groups yet.</p>{/if}</div></section>
{#if creating || editing}<div class="backdrop"><form class="dialog" onsubmit={(event) => { event.preventDefault(); void save(); }}><header><h2>{editing ? 'Edit equivalence group' : 'New equivalence group'}</h2><button type="button" aria-label="Close" onclick={() => { creating = false; editing = null; }}>×</button></header><label>Group name<input required bind:value={name}/></label><label>Notes (optional)<input bind:value={notes}/></label><label>Search part number<input aria-label="Search part number" placeholder="Search by part number" bind:value={query} onkeydown={(event) => { if (event.key === 'Enter') { event.preventDefault(); addMember(); } }}/></label><button class="secondary add" type="button" onclick={addMember}>Add part</button><p class="muted">Part numbers are searchable while you type; add at least two catalog part numbers before saving.</p><ul>{#each members as member}<li>{member}<button type="button" aria-label={`Remove ${member}`} onclick={() => members = members.filter((value) => value !== member)}>×</button></li>{/each}</ul>{#if error}<p class="error" role="alert">{error}</p>{/if}<footer><button type="button" class="secondary" onclick={() => { creating = false; editing = null; }}>Cancel</button><button class="primary" disabled={members.length < 2}>Save group</button></footer></form></div>{/if}
{#if deleting}<div class="backdrop"><div class="dialog small" role="dialog" aria-modal="true"><h2>Delete {deleting.name}?</h2><p>This removes the substitution rule from future matches.</p><button class="danger" onclick={() => void remove()}>Delete group</button><button class="secondary" onclick={() => deleting = null}>Cancel</button></div></div>{/if}
<style>.panel{padding:18px;border:1px solid var(--line);background:var(--surface)}.heading{display:flex;justify-content:space-between;gap:12px;align-items:start}.heading h2{margin:0}.eyebrow{margin:0 0 4px;color:var(--red);font-size:.7rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.muted{color:var(--ink-muted);font-size:.84rem}.groups article{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-top:1px solid var(--line)}.groups p{margin:4px 0;font-size:.84rem}.groups small{color:var(--ink-muted)}button{padding:7px 9px;border:1px solid var(--ink);font-weight:750;cursor:pointer}.primary{background:var(--red);color:white}.secondary{background:var(--surface)}.danger{margin-left:6px;background:#fff0ef;color:#8b1c28}.error{color:#8b1c28;font-size:.84rem}.backdrop{position:fixed;z-index:10;inset:0;display:grid;place-items:center;padding:16px;background:#17171777}.dialog{width:min(500px,100%);padding:20px;border:1px solid var(--ink);background:var(--surface);box-shadow:6px 6px #171717}.dialog header{display:flex;justify-content:space-between}.dialog h2{margin-top:0}.dialog label{display:grid;gap:5px;margin:10px 0;font-size:.8rem;font-weight:750}.dialog input{padding:8px;border:1px solid var(--line)}.add{margin-top:-4px}.dialog ul{padding-left:0;list-style:none}.dialog li{display:flex;justify-content:space-between;padding:6px;border-bottom:1px solid var(--line)}.dialog li button{padding:0 5px;border:0;background:none}.dialog footer{display:flex;justify-content:end;gap:8px;margin-top:14px}.small{max-width:400px}</style>
